name: example-environment
channels:
  - conda-forge
dependencies:
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - python=3.6
  - numpy=1.16
  - pandas=0.24
  - matplotlib=3.0
  - seaborn=0.9
  - jupyterlab=1.1
  - scikit-learn=0.21
  - pip
